// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace BookManagementSystem.Entity
{
    public partial class admin_Login
    {
        [Key]
        public int Login_Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Username { get; set; }
        [Required]
        [StringLength(50)]
        public string password { get; set; }
        public bool Is_Deleted { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Create_Time_Stamp { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Update_Time_Stamp { get; set; }
    }
}