// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace BookManagementSystem.Entity
{
    public partial class author_Name
    {
        public author_Name()
        {
            book_Details = new HashSet<book_Details>();
        }

        [Key]
        public int Author_Id { get; set; }
        [Required]
        [StringLength(100)]
        public string Book_Author { get; set; }
        public bool Is_Deleted { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Create_Time_Stamp { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Update_Time_Stamp { get; set; }

        [InverseProperty("Book_AuthorNavigation")]
        public virtual ICollection<book_Details> book_Details { get; set; }
    }
}