// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace BookManagementSystem.Entity
{
    public partial class book_Details
    {
        [Key]
        public int Book_Id { get; set; }
        [Required]
        [StringLength(150)]
        public string Book_Title { get; set; }
        public int Book_Author { get; set; }
        [Column(TypeName = "decimal(8, 2)")]
        public decimal Price { get; set; }
        public bool Is_Deleted { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Create_Time_Stamp { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Update_Time_Stamp { get; set; }

        [ForeignKey(nameof(Book_Author))]
        [InverseProperty(nameof(author_Name.book_Details))]
        public virtual author_Name Book_AuthorNavigation { get; set; }
    }
}